pool:
  vmImage: vs2017-win2016
variables:
  buildConfiguration: Release
name: 2.0.0.$(Rev:.r)
steps:
  - task: DotNetCoreCLI@2
    displayName: ".NET build"
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: --configuration $(BuildConfiguration)
  - script: dir
    workingDirectory: $(Agent.BuildDirectory)
    displayName: List contents of a folder
  - script: |
      "C:\Program Files\Microsoft SQL Server\130\Tools\Binn\SqlLocalDB.exe" create "v13.0" 13.0 -s 
    displayName: Starting SQL
  - task: DotNetCoreCLI@2
    displayName: ".NET test"
    inputs:
      command: test
      projects: '**/TestEase.Tests.csproj'
  - task: DotNetCoreCLI@2
    condition: succeededOrFailed()
    inputs:
      command: pack
      arguments: --configuration $(BuildConfiguration)
      packagesToPack: '**/TestEase.csproj'
      versioningScheme: byEnvVar
      versionEnvVar: Build.BuildNumber
      verbosityPack: detailed
  - task: PublishBuildArtifacts@1
