pool:
  vmImage: vs2017-win2016
variables:
  buildConfiguration: Release
steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: build
      Configuration: $(buildConfiguration)
  # - script: >
  #     dotnet build TestEase.sln --configuration $(buildConfiguration)
  #     dotnet test TestEase.Tests\TestEase.Tests.csproj --configuration $(buildConfiguration) --logger trx
  # - task: PublishTestResults@2
  #   condition: succeededOrFailed()
  #   inputs:
  #     testRunner: VSTest
  #     testResultsFiles: '**/*.trx'
  - task: DotNetCoreCLI@2
    condition: succeededOrFailed()
    inputs:
      command: pack
      configuration: $(buildConfiguration)
      packagesToPack: '**/TestEase.csproj'
      versioningScheme: byEnvVar
      versionEnvVar: Build.BuildNumber
      verbosityPack: detailed
  - task: PublishBuildArtifacts@1
